"""
Deterministic, zero-network, zero-cost implementation of ReviewPipelinePort. This is the
actual unlock Phase 0 exists for: every test that exercises "what happens when a review
completes/fails" can now run in milliseconds instead of ~6 minutes and real OpenAI spend.

Emits the same 11 node names in the same order as the real graph
(src/agents/orchestrator.py) — including the TAQA/ADM avl_check vs skip_avl branch — so
code that reacts to specific stage names (submittal_events writes, the frontend's phase
grouping) gets tested against realistic data, not a fake shape.
"""
from __future__ import annotations

from collections.abc import Callable

from core.errors import AppError
from core.models import ReviewRequest, ReviewResult
from core.ports import ReviewPipelinePort

_NODE_SEQUENCE_TEMPLATE = [
    "doc_processor",
    "completeness",
    "boq_drawing",
    "spec_verifier",
    "validity_checker",
    None,  # avl_check (TAQA) or skip_avl (ADM) — filled in per-request
    "statement",
    "table_auditor",
    "consistency",
    "others",
    "report_compiler",
]


def _default_report(request: ReviewRequest) -> dict:
    return {
        "submittal_id": request.submittal_id,
        "authority": request.authority,
        "material_description": "Fake material for testing",
        "spec_clause": "00 00 00",
        "review_date": request.review_date,
        "completeness_findings": [],
        "boq_drawing_findings": [],
        "spec_verification_findings": [],
        "validity_findings": [],
        "avl_findings": [],
        "statement_findings": [],
        "table_audit_findings": [],
        "consistency_findings": [],
        "others_findings": [],
        "critical_count": 0,
        "warning_count": 0,
        "missing_documents": [],
        "overall_recommendation": "APPROVE",
        "summary_comments": "Fake review — generated by FakeReviewPipeline, not a real assessment.",
    }


class FakeReviewPipeline(ReviewPipelinePort):
    def __init__(
        self,
        result: ReviewResult | None = None,
        raises: AppError | None = None,
    ) -> None:
        """
        result  — returned on success. Defaults to a minimal, valid, all-clear report.
        raises  — if set, `run()` raises this after emitting all stage-complete callbacks,
                  so tests can exercise "the pipeline ran partway then failed" without
                  needing a real failure.
        """
        self._result = result
        self._raises = raises

    def run(
        self,
        request: ReviewRequest,
        on_stage_complete: Callable[[str], None],
    ) -> ReviewResult:
        avl_node = "avl_check" if request.authority == "TAQA" else "skip_avl"
        for node_name in _NODE_SEQUENCE_TEMPLATE:
            on_stage_complete(node_name or avl_node)

        if self._raises is not None:
            raise self._raises

        return self._result or ReviewResult(report=_default_report(request))
